id: IC2244000
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:33:44+00:00'
last_modified: '2022-06-08T04:51:25.582370+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13840
  title: རྫ་སྟེང་ཆེན་དགོན་མདོ་སྔགས་བསྟན་རྒྱས་གླིང་གི་བྱུང་བ་བརྗོད་པ་ངོ་མཚར་གསེར་གྱི་གླིང་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E484:
      image_group_id: I1KG18522
      title: ''
      total_pages: 164
      order: 1
      base_file: E484.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
