id: IC2244000
legacy_id: P005551
ocr_import_info:
  bdrc_scan_id: W1KG13840
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T13:32:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T04:57:36.756875+00:00'
last_modified: 2022-08-27 12:57:54.879423
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG13840
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG13840
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྫ་སྟེང་ཆེན་དགོན་མདོ་སྔགས་བསྟན་རྒྱས་གླིང་གི་བྱུང་བ་བརྗོད་པ་ངོ་མཚར་གསེར་གྱི་གླིང་བུ།
  author: ཚེ་རིང་འགྱུར་མེད།
statistics:
  ocr_word_mean_confidence_index: 0.9120011347684098
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG18522:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18522
      total_pages: 164
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG18522.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9120011347684098
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
