id: P005551
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:58:52.624594
source_metadata:
  id: bdr:W1KG13840
  title: རྫ་སྟེང་ཆེན་དགོན་མདོ་སྔགས་བསྟན་རྒྱས་གླིང་གི་བྱུང་བ་བརྗོད་པ་ངོ་མཚར་གསེར་གྱི་གླིང་བུ།
  author: ''
  volumes:
    031477b8ce624436aae1a99d7c35a801:
      image_group_id: I1KG18522
      title: ''
      volume_number: 1
      total_pages: 164
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
