id: P005551
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13840
  title: རྫ་སྟེང་ཆེན་དགོན་མདོ་སྔགས་བསྟན་རྒྱས་གླིང་གི་བྱུང་བ་བརྗོད་པ་ངོ་མཚར་གསེར་གྱི་གླིང་བུ།
  author: ''
  volumes:
    031477b8ce624436aae1a99d7c35a801:
      image_group_id: I1KG18522
      title: ''
      volume_number: 1
      total_pages: 164
