id: opecha:P005551
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13840
  title: རྫ་སྟེང་ཆེན་དགོན་མདོ་སྔགས་བསྟན་རྒྱས་གླིང་གི་བྱུང་བ་བརྗོད་པ་ངོ་མཚར་གསེར་གྱི་གླིང་བུ།
  volume: ''
  author: ''
